sudo: false
dist: xenial
language: python
group: edge

services:
  - xvfb

matrix:
  include:
    - os: linux
      python: 3.5
      env: TESTENV=py35-pyqt571 QT_API=pyqt5 PEP8=1 COV=1
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install ffmpeg
  - export DISPLAY=:99.0
  - sleep 3

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/build/videomorph/videomorph/.cache

install:
  - pip install pip --upgrade
  - pip install nose flake8 pep8-naming flake8-debugger flake8-docstrings codecov
  - pip install PyQt5==5.7.1

script:
  - flake8 --select=D1 videomorph/*.py

after_success:
  - nosetests --with-coverage
  - codecov
